//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExpensesV2Entities : DbContext
    {
        public ExpensesV2Entities()
            : base("name=ExpensesV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AccountsStatements> AccountsStatements { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<ExchangeRates> ExchangeRates { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vAccounts> vAccounts { get; set; }
    
        [DbFunction("ExpensesV2Entities", "udf_TableFromString")]
        public virtual IQueryable<udf_TableFromString_Result> udf_TableFromString(string paramaterList)
        {
            var paramaterListParameter = paramaterList != null ?
                new ObjectParameter("ParamaterList", paramaterList) :
                new ObjectParameter("ParamaterList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_TableFromString_Result>("[ExpensesV2Entities].[udf_TableFromString](@ParamaterList)", paramaterListParameter);
        }
    
        public virtual ObjectResult<RPT_GetAccounts_Result> RPT_GetAccounts(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_GetAccounts_Result>("RPT_GetAccounts", yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<RPT_Months_Result> RPT_Months()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RPT_Months_Result>("RPT_Months");
        }
    
        public virtual ObjectResult<string> RPT_Years()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RPT_Years");
        }
    }
}
