//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccounts
    {
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Liquid { get; set; }
        public string AccountDescription { get; set; }
        public string BankShortName { get; set; }
        public string BankName { get; set; }
        public string CurrencyDescription { get; set; }
        public string CodCurrency { get; set; }
        public string Pessoa { get; set; }
        public decimal Value { get; set; }
        public int month { get; set; }
        public int year { get; set; }
    }
}
