//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.AccountsStatements = new HashSet<AccountsStatements>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public int idBank { get; set; }
        public string CodCurrency { get; set; }
        public string CodAccountType { get; set; }
        public Nullable<bool> Liquid { get; set; }
        public Nullable<int> idPessoa { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Banks Banks { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsStatements> AccountsStatements { get; set; }
    }
}
