//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int id { get; set; }
        public string Description { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int SubType { get; set; }
        public decimal Value { get; set; }
        public string Observations { get; set; }
    }
}
