//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortages
    {
        public long id { get; set; }
        public Nullable<double> Euribor { get; set; }
        public Nullable<double> Spread { get; set; }
        public Nullable<decimal> RemainingValue { get; set; }
        public System.DateTime Date { get; set; }
        public decimal payment { get; set; }
        public int IDSubType { get; set; }
    
        public virtual MortagesSubTypes MortagesSubTypes { get; set; }
    }
}
